# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.lkj_cmit <- function(k, y) {
    .Call(`_lkj_lkj_cmit`, k, y)
}

ljk_par <- function(w) {
    .Call(`_lkj_ljk_par`, w)
}

