# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cvine_cholesky_cpp <- function(v, d, eta = 1.0) {
    .Call(`_lkj_cvine_cholesky`, v, d, eta)
}

onion_cholesky_cpp <- function(v, d, eta = 1.0) {
    .Call(`_lkj_onion_cholesky_impl`, v, d, eta)
}

